spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3307/roki?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql

  
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/roki?serverTimezone=UTC&characterEncoding=UTF-8
    user: root
    password: root

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace