version: '3'

services:
  roki-mysql:
    image: mysql:8.0.28
    container_name: roki-mysql
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=roki
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
      - ./volumes/mysql-log:/var/log/mysql
      - ./config/my-conf.cnf:/etc/mysql/conf.d/my-conf.cnf
    platform: linux/x86_64
